import Navbar from '@/app/components/Navbar'
import './globals.css'
import { Poppins } from 'next/font/google'

const poppins = Poppins({
  subsets: ['latin'],
  weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900'],
})

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang='en' className={poppins.className}>
      <body className=''>
        <main className='lg:py-[.5rem]  '>{children}</main>
        <header>
          <Navbar />
        </header>
      </body>
    </html>
  )
}
